spring:
  datasource:
    url: jdbc:mysql://localhost:3306/online_shop?serverTimezone=UTC
    username: root
    password: Kamil
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      database: mysql
      database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false